# -*- coding: utf-8 -*-
"""CodigosdoPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5N-cp4JENwDLfYPklXMRtmZIJpD8XpP

Tipos de Dados
idade guarda o valor
25 e
nome guarda o valor
"João" .
Os tipos de dados são como as diferentes formas que nossos dados podem assumir. No Python, temos vários tipos de dados, incluindo:
int (inteiro):
idade = 25
float (número de ponto flutuante):
altura = 1.75
str (string, ou cadeia de caracteres):
nome = "João"
bool (booleano, que pode ser Verdadeiro ou Falso):
tem_cachorro = True
"""

Age = 16
print("Minha idade e" ,Age, "anos")

Altura = 1.80
print(Altura)

nome = 'Gabriel'
sobrenome = 'Cruz Costa'
print(nome, sobrenome)

tem_relacionamento = True # verdadeiro
E_hommosexual = False # falso
print("tem relacionamento?", tem_relacionamento)
print("E homosexual??", E_hommosexual)

print(
    type(Age) #int - numero inteiro - integer
)
print(
    type(Altura) #float - numero quebrado/flutuante - floating
)
print(
    type(nome) #str - string - cojunto de caracteres Ex:ABC12345@%
)
print(type (sobrenome)) #str - string - cojunto de caracteres Ex:ABC12345@%)
print(type (tem_relacionamento)) #bool - verdadeiro/falso
print(type (E_hommosexual))     #bool - verdadeiro/falso

idade = 21
print("A idade do rapaz e" ,idade, "anos.")
# f string  / tamplete string
print(f"A idade do rapaz e {idade} anos.")

texto = '1'
texTo = 1
print(type (texto))
print(type (texTo))

Nome = 'Gabriel'
cidade_estado = 'Fortaleza Ceara'
idade = 16
altura = 1,68
clima = 'chuvoso'
print(f'meu nome e {Nome}, eu moro em {cidade_estado}' )
print(f"tenho {idade} anos e tenho {altura} de altura,")
print(f'hoje o dia estava {clima}.' )

"""Operadores Aritméticos
Os operadores aritméticos são como as operações matemáticas que aprendemos na escola. Eles incluem:
+ (Adição): 5 + 3 é igual a 8.- (Subtração): 10 - 7 é igual a 3.
* (Multiplicação): 4 * 2 é igual a 8.
/ (Divisão): 9 / 3 é igual a 3.
% (Módulo): 10 % 3 é igual a 1, pois é o resto da divisão de 10 por 3.
** (Exponenciação): 2 ** 3 é igual a 8, pois é 2 elevado à potência de 3
"""

laranja = 6
acerola = 4
frutas = laranja + acerola
print(f'Eu temho {laranja} laranjas e {acerola}.')
print(f'Entao no total eu tenho {frutas} frutas.')

meu_saldo = 15
maconha = 10
troco = meu_saldo - maconha
print(f'meu troco e de {troco} reais.')

preco_unitario_produto = 7
quantidade = 2
valor_final = preco_unitario_produto * quantidade
print(f'O valor da compra e de {valor_final} reais.')

valor_total = 60
quantidade_de_amigos = 3
valor_dividido = valor_total / (quantidade_de_amigos+1)
print(f'O valor que cada um deve pagar e de {valor_dividido} reais.')

par_de_sapato = 2
quantidade_de_pares = 3
unidades_de_sapato = par_de_sapato ** quantidade_de_pares
print(f'A quantidade de unidades de sapatos e de {unidades_de_sapato}.')

quantidade_paes = 5
quantidade_pessoas = 2
quanto_restante_de_paes = quantidade_paes % quantidade_pessoas
print(f'A quantidade de paes restantes e de {quanto_restante_de_paes} pao.')

"""
Abreviações de Operadores Aritméticos
exemplo:
1. +=
2. -=
3. /=

"""

maca = 5
maca += 4   #forma de abreviar adicao
print(maca)

preco = 15
quantidade = 3  # "*=" para abreviar multiplicacao
preco *= quantidade
print(f'O valor total e de {preco} reais.')

"""Operadores de Comparação
Os operadores de comparação são usados para comparar valores. Eles são como perguntas que fazemos ao Python. Eles incluem:
== (Igual a): 5 == 3 retorna False, pois 5 não é igual a 3.
!= (Diferente de): 5 != 3 retorna True, pois 5 é diferente de 3.
> (Maior que): 5 > 3 retorna True, pois 5 é maior que 3.
< (Menor que): 5 < 3 retorna False, pois 5 não é menor que 3.
>= (Maior ou igual a): 5 >= 5 retorna True, pois 5 é maior ou igual a 5.
<= (Menor ou igual a): 5 <= 3 retorna False, pois 5 não é menor ou igual a 3
"""

5 == 3 #(igual a)

5 != 3 #(diferente de)

5 > 3 #(maior que)

5 < 3 #(menor que)

5 >= 3 #(maior ou igual)

5 <= 3 #(menor ou igual)

variavel_1 = 10
variavel_2 = '10' #"=" e usado para atribuir valor a uma variavel, enquanto == e usado para comparar dois valores
resultado = variavel_1 == variavel_2
print(type(variavel_1))
print(type(variavel_2))
print(resultado)

variavel_1 = 5
variavel_2 = 5.1 #"=" e usado para atribuir valor a uma variavel, enquanto == e usado para comparar dois valores
resultado = variavel_1 == variavel_2
print(type(variavel_1))
print(type(variavel_2))
print(resultado)

variavel_1 = 1 #0 = a False, 1 igual a True
variavel_2 = True #"=" e usado para atribuir valor a uma variavel, enquanto == e usado para comparar dois valores
resultado = variavel_1 == variavel_2
print(type(variavel_1))
print(type(variavel_2))
print(resultado)

"""Operadores Lógicos
Os operadores lógicos são usados para combinar condições. Eles são como conjunções que usamos para combinar frases. Eles incluem:
and (E): 5 > 3 and 5 > 4 retorna True, pois ambas as condições são verdadeiras.
or (OU): 5 > 3 or 5 < 4 retorna True, pois pelo menos uma das condições é verdadeira.
not (NÃO): not 5 < 3 retorna True, pois 5 não é menor que 3.
"""

5 > 3 and 5 < 6 #(Verdadeiro pois 5 e maior que 3 e 5 e menor que 6)

5 > 3 and 5 < 5 #(falso pois apesar do primeiro resultado estar correto 5 nao e menor que 5) nao importa se tem uma correta se alguma estivar dando como falsa, o codigo inteiro e comprometido

5 > 3 or 5 < 5 #(Verdadeira pois com o "or" com apenas uma sendo verdadeira o codigo vai ser verdade, diferente do "and")

a = 5 > 3
b = 5 < 5  #(Verdadeira pois com o "or" com apenas uma sendo verdadeira o codigo vai ser verdade, diferente do "and")
print(a)
print(b)
print(a or b)

a = 5 > 3
b = 5 < 5 #(com o and nao da certo pois apenas uma variavel esta correta)
print(a)
print(b)
print(a and b)

a = 5 > 3
b = 5 < 5 #(O "not" ele muda o valor da A por exemplo que era true, para False)
print(not a)
print(b)
print(a or b)

a = 5 > 3
b = 5 < 5 #(mesmo estando "errado" por causa do not vai dar como verdadeiro)
print(a)
print(b)
print(a and not b)

"""Estruturas de Decisão
As estruturas de decisão são como encruzilhadas na estrada. Dependendo de uma condição, o programa pode seguir um caminho ou outro.
No Python, usamos if, elif e
else para criar essas estruturas.
exemplo:
idade = 20
if idade < 18:
print("Menor de idade.")
elif idade == 18:
print("Acabou de se tornar maior de idade.")
else:
print("Maior de idade.")

"""

idade = 19

if idade < 18:                   #estrutura de decisao, "if" para 'se'. else para "senao" e elif para "Se nao, se"
  print('Menor de idade.')
elif idade == 18:
  print('Acabou de se tornar maior de idade.')
else:
  print('Maior de idade.')

idade = 17

if idade < 18:                  #(Outra forma de usar o mesmo codigo so que com o else no lugar do elif)
  print('Menor de idade.')
else:
  if idade == 18:
   print('Acabou de se tornar maior de idade.')
  else:
   print('Maior de idade.')

esta_chuvendo = True
tenho_guarda_chuva = False

if esta_chuvendo and not tenho_guarda_chuva:
  print('Vou me molhar!')

elif esta_chuvendo and tenho_guarda_chuva:
  print('Nao vou me molhar pois tenho um guarda chuva')

elif not esta_chuvendo and not tenho_guarda_chuva:
  print('Nao vou me molhar pois nao esta chuvendo e nao tenho guarda-chuva')

else:
  print('Chuva? Nao acredito que va chover...')

esta_chuvendo = False
tenho_guarda_chuva = True

if esta_chuvendo and not tenho_guarda_chuva:
  print('Vou me molhar!')

elif esta_chuvendo and tenho_guarda_chuva:
  print('Nao vou me molhar pois tenho um guarda chuva')

elif not esta_chuvendo and not tenho_guarda_chuva:
  print('Nao vou me molhar pois nao esta chuvendo e nao tenho guarda-chuva')

else:
  print('Chuva? Nao acredito que va chover...')

"""Estruturas de repeticao
As estruturas de repeticao sao como voltas em uma corrida. Elas permitem que o progama repita um bloco de codigo varias vezes. No python temos for e while para criar essas estruturas
"""

contador = 0
while contador < 10:       #(wilhe sgnifica "enquanto" exemplo de um contador de 1 ate 10)
   contador +=1
   print(contador)

contador = 0
while contador < 10:       #forma diferente de ter o mesmo resultado
   contador = contador + 1
   print(contador)

"""Agora o for, usamos para cada item em um determinado range = intervalo/periodo
usamos ambos para repetir uma acao por determinado periodo
o while executa uma acao cada vez que a expressao for verdadeira, caso ela mude para falso ela vai parar de executar a acao.
ja o for nos conseguimos definir des de o inicio qual e o periodo que ele vai executar. (Lembrando que o for e N-1,)
"""

contador = 0
while contador <= 15:      #A frase print de baixo nao esta na funcao de repeticao do while porque esta sendo escrita no primeiro espaco da linha, caso eu der 3 espacos e escrever o comando ele vai
                          #entrar na funcao de repeticao do while
   contador +=1
   print(contador)
print("peardi as bolas")

for contador in range(1, 11): #usando o "range" precisamos sempre colocar 1 numero a mais do que queremos, que nesse caso e 10 entao eu coloco 11 pq o range sempre subtrai 1
   print(contador)

"""Metodo chines de depuracao ou chineszinho sla
olhar para o codigo e tentar entender passo a passo dele, mesmo sem executar.




"""

total_pares = 0                         #todos os numero pares de 1 ate 10
for numero in range(1, 11):
  if numero % 2 == 0:
       total_pares += 1

print(f'total de numeros pares: {total_pares} ')


total_pares_while = 0
numero_while = 0
while numero_while < 10:
  if numero_while % 2 == 0:
    total_pares_while += 1
  numero_while = numero_while + 1

print(f'Total de numeros pares: {total_pares_while} ' )

X = int(input())                #int = serve para transformar a variavel em inteiro, no caso sem esse int ela estaria como 'str' cojunto de caracteres
print(type(X))

print('Tabuada usando o FOR')
for numero_multiplicador in range(1, 11):                  #tabuada ate o 10 usando o 'for'
  resultado = X * numero_multiplicador
  print(f' {X} x {numero_multiplicador} = {resultado}')

print('Tabuada usando o WHILE')
numero_multiplicador = 1
while numero_multiplicador <= 10:                               #tabuada ate o 10 usando o while
  resultado = X * numero_multiplicador
  print(f'{X} x {numero_multiplicador} = {resultado}')
  numero_multiplicador += 1

""" Funções
 São blocos de codigos que executam uma tarefa especifica e que podem ser reutilizaveis.

 Esses blocos de codigos possuem funções especificar, por isso, chamamos de funções

 Cada função pode ter nome;titulo

 Exemplo:

 A Função print(), nativa do python, pode imprimir um resultado na tela.

 Para definir uma função em Python, Usamos o termo:

 def
"""

variavel = 1
def escrever_na_tela(valor):
  valor = valor + '!'
  print(valor)

escrever_na_tela('Ola, meu nome e Kurt Cobain')
print('Ola, meu nome e Kurt Cobain')

def somar(numero1, numero2):
  resultado = numero1 + numero2
  return resultado

  resultado_soma = somar(3, 5)
  print(f'A soma e: {resultado_soma} ' )

def somar(number1, number2):
  resultado = number1 + number2
  return resultado

resultado_soma = somar(3, 5)
print(f'A soma e: {resultado_soma}')
resultado_soma = somar(5, 4)
print(f'A soma e: {resultado_soma}')
resultado_soma = somar(2, 4)
print(f'A soma e: {resultado_soma}')

def verifica_se_eh_par(numero):
  if numero % 2 == 0:
    return True
  else:
    return False

numero = 3
if verifica_se_eh_par(numero):
  print(f'{numero} E um numero par.')
else:
  print(f'{numero} Nao e um numero par.')

def saudacao(nome):
  return f'Ola {nome} Como voce esta?'

nome_do_usuario = input('Qual e o seu nome?')
mensagem = saudacao (nome_do_usuario)
print(mensagem)

jogador1 = input('--> Digite o nome do jogador 1')
jogador2 = input('--> Digite o nome do jogador 2')

print(f'--> Quem escolhe primeiro, {jogador1} ou {jogador2} ?')
primeiro_jogador = input(f'--> Digite 1 para escolher {jogador1} ou digite 2 para escolher {jogador2}.')
segundo_jogador = None

if primeiro_jogador == "1":
  primeiro_jogador = jogador1
  segundo_jogador = jogador2
elif primeiro_jogador == "2":
  primeiro_jogador = jogador2
  segundo_jogador = jogador1

print('--> Digite 0 para escolher PAR ou digite 1 para escolher IMPAR')
escolha = input(f'{primeiro_jogador} Voce quer par ou impar?')
escolha2 = None

if escolha == 'impar' or escolha == 'Impar' or escolha == '1':
  escolha = 'impar'
  escolha2 = 'par'
elif escolha == 'par' or escolha == '0':
  escolha = 'par'
  escolha2 = 'impar'

print(f'--> {segundo_jogador}, Voce ficou com a {escolha2}.')

numero1 = int(input(f'--> {primeiro_jogador}, escolha um numero:'))
numero2 = int(input(f'--> {segundo_jogador}, escolha um numero:'))

soma = numero1 + numero2

if soma % 2 == 0:
  vencedor = 'par'
else:
  vencedor = 'impar'

if vencedor == escolha:
  print(f'--> {primeiro_jogador} Venceu!')
else:
  print(f'--> {segundo_jogador} Venceu!')

"""Exercicios para estimular o megabrain"""

def saudacao(nome):
 return f'OLa, {nome} bem vindo a biqueira'

nome_do_usuario = input('Ola, qual e seu nome?')
mensagem = saudacao(nome_do_usuario)
print(mensagem)

Age = input(f'E qual e sua idade {nome_do_usuario}?')

print(f'Bem vindo a area verde {nome_do_usuario} e sua iadade e de {Age} anos.')

num1 = int(input('Digite um numero.'))
num2 = int(input("Digite um numero."))

resultado_soma = num1 + num2
resultado_subtracao = num1 - num2

print(resultado_soma)
print(resultado_subtracao)

torta_de_frango = 5
dinheiro = int(input('Quanto voce tem?'))
if dinheiro < 5:
  print('Voce nao tem dinheiro suficiente para comprar uma torta de frango.')
if dinheiro >= 5:
  print('Voce tem dinheiro suficiente para 1 torta de frango.')

preco_do_pao = 4
dinheiro_disponivel = float(input('Quanto dinheiro voce tem?'))

if dinheiro_disponivel >= preco_do_pao:
  print('Vai comer o pao que o diabo amassou kkkkk')
else:
 print('Entao nao vai comer porrra nenhuma kkkkkkkk')

temperatura = int(input('Quantos graus esta fazendoi?'))
if temperatura < 20:
  print('Friu do caraio veio kkkkkkkkkkkkkkkk')
elif temperatura >= 20 and temperatura <= 28:
  print('Ta suave fiah.')
else:
  print('Ta quente pra caralho, so no ceara mesmo kkkkk')

horario = int((20))
nome = 'Kurt cobain'

if horario >= 5 and horario <= 12:
  print(f'Bom dia {nome}.')

if horario >= 13 and horario <= 18:
  print(f'Boa tarde {nome}.')

elif horario >=19 and horario <=23:
  print(f'Boa noite {nome}.')

if horario >= 1 and horario == 5:
  print(f"Boa madrugada {nome}, so nao dorme tao tarde kkk")

horario = int(input('Que horas sao?'))
nome = input('Qual e seu nome?')

if horario >= 5 and horario <= 12:
  print(f'Bom dia {nome}.')

if horario >= 13 and horario <= 18:
  print(f'Boa tarde {nome}.')

elif horario >=19 and horario <=23:
  print(f'Boa noite {nome}.')

if horario >= 1 and horario == 5:
  print(f"Boa madrugada {nome}, so nao dorme tao tarde kkk")

idade = input('Qual sua idade?')
condicionamento_fisico = input("Tem condicao fisica?")
permissaomedica = input('Tem permissao medica?')

if condicionamento_fisico == 'sim':
 condicionamento_fisico = True or condicionamento_fisico == 'nao'
 condicionamento_fisico = False

if permissaomedica == 'sim':
  permissaomedica = True or permissaomedica == 'nao'
  permissaomedica = False

if idade >= 18 and (condicionamento_fisico for False and permissaomedica True):
  print('Pode fih')
else:
  print("Pode nao fiah")

lista = [True, 1, 1.23]
print(f'Tipo de um array: {type(lista)}')

lista_de_compras = ['Leite', 'Pao', 'Ovos']
print(f'Lista de compras: {lista_de_compras}')                #quando usamos esse simbolo "[]" caso eu queira acessar os intes dele, devo lembrar que eles sao contados da esquerda para a direita comecando com o 0, 1, 2

#sempre contando do 0
print(f'Item 1: {lista_de_compras[0]}')
print(f'Item 2: {lista_de_compras[1]}')
print(f'Item 3: {lista_de_compras[2]}')

#length = comprimento
print(len(lista))
print(len(lista_de_compras))

print(lista_de_compras [-1])

print(f'Item 1 lista: {type (lista[0])}')
print(f'Item 2 lista: {type (lista [1])}')
print(f'Item 3 lista: {type (lista [2])}')

print(lista[1:3])

lista_de_compras.append('Hamburger')
print(lista_de_compras)

lista_de_compras.pop()
print(lista_de_compras)

lista_de_compras.reverse()
print(lista_de_compras)

lista_de_compras.clear()
print(lista_de_compras)

for numero in range(1, 11):
  print(numero)

len(list(range(1, 11)))